// Code generated by ent, DO NOT EDIT.

package invoice

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/MartialM1nd/freefsm/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldID, id))
}

// CompanyID applies equality check predicate on the "company_id" field. It's identical to CompanyIDEQ.
func CompanyID(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCompanyID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCustomerID, v))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldJobID, v))
}

// EstimateID applies equality check predicate on the "estimate_id" field. It's identical to EstimateIDEQ.
func EstimateID(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldEstimateID, v))
}

// StatusID applies equality check predicate on the "status_id" field. It's identical to StatusIDEQ.
func StatusID(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldStatusID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldTitle, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldNotes, v))
}

// InvoiceDate applies equality check predicate on the "invoice_date" field. It's identical to InvoiceDateEQ.
func InvoiceDate(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldInvoiceDate, v))
}

// DueDate applies equality check predicate on the "due_date" field. It's identical to DueDateEQ.
func DueDate(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldDueDate, v))
}

// TaxRate applies equality check predicate on the "tax_rate" field. It's identical to TaxRateEQ.
func TaxRate(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldTaxRate, v))
}

// LineItems applies equality check predicate on the "line_items" field. It's identical to LineItemsEQ.
func LineItems(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldLineItems, v))
}

// Payments applies equality check predicate on the "payments" field. It's identical to PaymentsEQ.
func Payments(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldPayments, v))
}

// DisplaySettings applies equality check predicate on the "display_settings" field. It's identical to DisplaySettingsEQ.
func DisplaySettings(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldDisplaySettings, v))
}

// CustomFields applies equality check predicate on the "custom_fields" field. It's identical to CustomFieldsEQ.
func CustomFields(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCustomFields, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompanyIDEQ applies the EQ predicate on the "company_id" field.
func CompanyIDEQ(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCompanyID, v))
}

// CompanyIDNEQ applies the NEQ predicate on the "company_id" field.
func CompanyIDNEQ(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldCompanyID, v))
}

// CompanyIDIn applies the In predicate on the "company_id" field.
func CompanyIDIn(vs ...int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldCompanyID, vs...))
}

// CompanyIDNotIn applies the NotIn predicate on the "company_id" field.
func CompanyIDNotIn(vs ...int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldCompanyID, vs...))
}

// CompanyIDGT applies the GT predicate on the "company_id" field.
func CompanyIDGT(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldCompanyID, v))
}

// CompanyIDGTE applies the GTE predicate on the "company_id" field.
func CompanyIDGTE(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldCompanyID, v))
}

// CompanyIDLT applies the LT predicate on the "company_id" field.
func CompanyIDLT(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldCompanyID, v))
}

// CompanyIDLTE applies the LTE predicate on the "company_id" field.
func CompanyIDLTE(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldCompanyID, v))
}

// CompanyIDIsNil applies the IsNil predicate on the "company_id" field.
func CompanyIDIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldCompanyID))
}

// CompanyIDNotNil applies the NotNil predicate on the "company_id" field.
func CompanyIDNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldCompanyID))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDIsNil applies the IsNil predicate on the "customer_id" field.
func CustomerIDIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldCustomerID))
}

// CustomerIDNotNil applies the NotNil predicate on the "customer_id" field.
func CustomerIDNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldCustomerID))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldJobID, v))
}

// JobIDIsNil applies the IsNil predicate on the "job_id" field.
func JobIDIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldJobID))
}

// JobIDNotNil applies the NotNil predicate on the "job_id" field.
func JobIDNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldJobID))
}

// EstimateIDEQ applies the EQ predicate on the "estimate_id" field.
func EstimateIDEQ(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldEstimateID, v))
}

// EstimateIDNEQ applies the NEQ predicate on the "estimate_id" field.
func EstimateIDNEQ(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldEstimateID, v))
}

// EstimateIDIn applies the In predicate on the "estimate_id" field.
func EstimateIDIn(vs ...int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldEstimateID, vs...))
}

// EstimateIDNotIn applies the NotIn predicate on the "estimate_id" field.
func EstimateIDNotIn(vs ...int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldEstimateID, vs...))
}

// EstimateIDGT applies the GT predicate on the "estimate_id" field.
func EstimateIDGT(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldEstimateID, v))
}

// EstimateIDGTE applies the GTE predicate on the "estimate_id" field.
func EstimateIDGTE(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldEstimateID, v))
}

// EstimateIDLT applies the LT predicate on the "estimate_id" field.
func EstimateIDLT(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldEstimateID, v))
}

// EstimateIDLTE applies the LTE predicate on the "estimate_id" field.
func EstimateIDLTE(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldEstimateID, v))
}

// EstimateIDIsNil applies the IsNil predicate on the "estimate_id" field.
func EstimateIDIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldEstimateID))
}

// EstimateIDNotNil applies the NotNil predicate on the "estimate_id" field.
func EstimateIDNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldEstimateID))
}

// StatusIDEQ applies the EQ predicate on the "status_id" field.
func StatusIDEQ(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldStatusID, v))
}

// StatusIDNEQ applies the NEQ predicate on the "status_id" field.
func StatusIDNEQ(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldStatusID, v))
}

// StatusIDIn applies the In predicate on the "status_id" field.
func StatusIDIn(vs ...int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldStatusID, vs...))
}

// StatusIDNotIn applies the NotIn predicate on the "status_id" field.
func StatusIDNotIn(vs ...int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldStatusID, vs...))
}

// StatusIDGT applies the GT predicate on the "status_id" field.
func StatusIDGT(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldStatusID, v))
}

// StatusIDGTE applies the GTE predicate on the "status_id" field.
func StatusIDGTE(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldStatusID, v))
}

// StatusIDLT applies the LT predicate on the "status_id" field.
func StatusIDLT(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldStatusID, v))
}

// StatusIDLTE applies the LTE predicate on the "status_id" field.
func StatusIDLTE(v int64) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldStatusID, v))
}

// StatusIDIsNil applies the IsNil predicate on the "status_id" field.
func StatusIDIsNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldIsNull(FieldStatusID))
}

// StatusIDNotNil applies the NotNil predicate on the "status_id" field.
func StatusIDNotNil() predicate.Invoice {
	return predicate.Invoice(sql.FieldNotNull(FieldStatusID))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldTitle, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldNotes, v))
}

// InvoiceDateEQ applies the EQ predicate on the "invoice_date" field.
func InvoiceDateEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldInvoiceDate, v))
}

// InvoiceDateNEQ applies the NEQ predicate on the "invoice_date" field.
func InvoiceDateNEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldInvoiceDate, v))
}

// InvoiceDateIn applies the In predicate on the "invoice_date" field.
func InvoiceDateIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldInvoiceDate, vs...))
}

// InvoiceDateNotIn applies the NotIn predicate on the "invoice_date" field.
func InvoiceDateNotIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldInvoiceDate, vs...))
}

// InvoiceDateGT applies the GT predicate on the "invoice_date" field.
func InvoiceDateGT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldInvoiceDate, v))
}

// InvoiceDateGTE applies the GTE predicate on the "invoice_date" field.
func InvoiceDateGTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldInvoiceDate, v))
}

// InvoiceDateLT applies the LT predicate on the "invoice_date" field.
func InvoiceDateLT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldInvoiceDate, v))
}

// InvoiceDateLTE applies the LTE predicate on the "invoice_date" field.
func InvoiceDateLTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldInvoiceDate, v))
}

// DueDateEQ applies the EQ predicate on the "due_date" field.
func DueDateEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldDueDate, v))
}

// DueDateNEQ applies the NEQ predicate on the "due_date" field.
func DueDateNEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldDueDate, v))
}

// DueDateIn applies the In predicate on the "due_date" field.
func DueDateIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldDueDate, vs...))
}

// DueDateNotIn applies the NotIn predicate on the "due_date" field.
func DueDateNotIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldDueDate, vs...))
}

// DueDateGT applies the GT predicate on the "due_date" field.
func DueDateGT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldDueDate, v))
}

// DueDateGTE applies the GTE predicate on the "due_date" field.
func DueDateGTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldDueDate, v))
}

// DueDateLT applies the LT predicate on the "due_date" field.
func DueDateLT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldDueDate, v))
}

// DueDateLTE applies the LTE predicate on the "due_date" field.
func DueDateLTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldDueDate, v))
}

// TaxRateEQ applies the EQ predicate on the "tax_rate" field.
func TaxRateEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldTaxRate, v))
}

// TaxRateNEQ applies the NEQ predicate on the "tax_rate" field.
func TaxRateNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldTaxRate, v))
}

// TaxRateIn applies the In predicate on the "tax_rate" field.
func TaxRateIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldTaxRate, vs...))
}

// TaxRateNotIn applies the NotIn predicate on the "tax_rate" field.
func TaxRateNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldTaxRate, vs...))
}

// TaxRateGT applies the GT predicate on the "tax_rate" field.
func TaxRateGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldTaxRate, v))
}

// TaxRateGTE applies the GTE predicate on the "tax_rate" field.
func TaxRateGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldTaxRate, v))
}

// TaxRateLT applies the LT predicate on the "tax_rate" field.
func TaxRateLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldTaxRate, v))
}

// TaxRateLTE applies the LTE predicate on the "tax_rate" field.
func TaxRateLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldTaxRate, v))
}

// TaxRateContains applies the Contains predicate on the "tax_rate" field.
func TaxRateContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldTaxRate, v))
}

// TaxRateHasPrefix applies the HasPrefix predicate on the "tax_rate" field.
func TaxRateHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldTaxRate, v))
}

// TaxRateHasSuffix applies the HasSuffix predicate on the "tax_rate" field.
func TaxRateHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldTaxRate, v))
}

// TaxRateEqualFold applies the EqualFold predicate on the "tax_rate" field.
func TaxRateEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldTaxRate, v))
}

// TaxRateContainsFold applies the ContainsFold predicate on the "tax_rate" field.
func TaxRateContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldTaxRate, v))
}

// LineItemsEQ applies the EQ predicate on the "line_items" field.
func LineItemsEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldLineItems, v))
}

// LineItemsNEQ applies the NEQ predicate on the "line_items" field.
func LineItemsNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldLineItems, v))
}

// LineItemsIn applies the In predicate on the "line_items" field.
func LineItemsIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldLineItems, vs...))
}

// LineItemsNotIn applies the NotIn predicate on the "line_items" field.
func LineItemsNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldLineItems, vs...))
}

// LineItemsGT applies the GT predicate on the "line_items" field.
func LineItemsGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldLineItems, v))
}

// LineItemsGTE applies the GTE predicate on the "line_items" field.
func LineItemsGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldLineItems, v))
}

// LineItemsLT applies the LT predicate on the "line_items" field.
func LineItemsLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldLineItems, v))
}

// LineItemsLTE applies the LTE predicate on the "line_items" field.
func LineItemsLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldLineItems, v))
}

// LineItemsContains applies the Contains predicate on the "line_items" field.
func LineItemsContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldLineItems, v))
}

// LineItemsHasPrefix applies the HasPrefix predicate on the "line_items" field.
func LineItemsHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldLineItems, v))
}

// LineItemsHasSuffix applies the HasSuffix predicate on the "line_items" field.
func LineItemsHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldLineItems, v))
}

// LineItemsEqualFold applies the EqualFold predicate on the "line_items" field.
func LineItemsEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldLineItems, v))
}

// LineItemsContainsFold applies the ContainsFold predicate on the "line_items" field.
func LineItemsContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldLineItems, v))
}

// PaymentsEQ applies the EQ predicate on the "payments" field.
func PaymentsEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldPayments, v))
}

// PaymentsNEQ applies the NEQ predicate on the "payments" field.
func PaymentsNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldPayments, v))
}

// PaymentsIn applies the In predicate on the "payments" field.
func PaymentsIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldPayments, vs...))
}

// PaymentsNotIn applies the NotIn predicate on the "payments" field.
func PaymentsNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldPayments, vs...))
}

// PaymentsGT applies the GT predicate on the "payments" field.
func PaymentsGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldPayments, v))
}

// PaymentsGTE applies the GTE predicate on the "payments" field.
func PaymentsGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldPayments, v))
}

// PaymentsLT applies the LT predicate on the "payments" field.
func PaymentsLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldPayments, v))
}

// PaymentsLTE applies the LTE predicate on the "payments" field.
func PaymentsLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldPayments, v))
}

// PaymentsContains applies the Contains predicate on the "payments" field.
func PaymentsContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldPayments, v))
}

// PaymentsHasPrefix applies the HasPrefix predicate on the "payments" field.
func PaymentsHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldPayments, v))
}

// PaymentsHasSuffix applies the HasSuffix predicate on the "payments" field.
func PaymentsHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldPayments, v))
}

// PaymentsEqualFold applies the EqualFold predicate on the "payments" field.
func PaymentsEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldPayments, v))
}

// PaymentsContainsFold applies the ContainsFold predicate on the "payments" field.
func PaymentsContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldPayments, v))
}

// DisplaySettingsEQ applies the EQ predicate on the "display_settings" field.
func DisplaySettingsEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldDisplaySettings, v))
}

// DisplaySettingsNEQ applies the NEQ predicate on the "display_settings" field.
func DisplaySettingsNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldDisplaySettings, v))
}

// DisplaySettingsIn applies the In predicate on the "display_settings" field.
func DisplaySettingsIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldDisplaySettings, vs...))
}

// DisplaySettingsNotIn applies the NotIn predicate on the "display_settings" field.
func DisplaySettingsNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldDisplaySettings, vs...))
}

// DisplaySettingsGT applies the GT predicate on the "display_settings" field.
func DisplaySettingsGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldDisplaySettings, v))
}

// DisplaySettingsGTE applies the GTE predicate on the "display_settings" field.
func DisplaySettingsGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldDisplaySettings, v))
}

// DisplaySettingsLT applies the LT predicate on the "display_settings" field.
func DisplaySettingsLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldDisplaySettings, v))
}

// DisplaySettingsLTE applies the LTE predicate on the "display_settings" field.
func DisplaySettingsLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldDisplaySettings, v))
}

// DisplaySettingsContains applies the Contains predicate on the "display_settings" field.
func DisplaySettingsContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldDisplaySettings, v))
}

// DisplaySettingsHasPrefix applies the HasPrefix predicate on the "display_settings" field.
func DisplaySettingsHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldDisplaySettings, v))
}

// DisplaySettingsHasSuffix applies the HasSuffix predicate on the "display_settings" field.
func DisplaySettingsHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldDisplaySettings, v))
}

// DisplaySettingsEqualFold applies the EqualFold predicate on the "display_settings" field.
func DisplaySettingsEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldDisplaySettings, v))
}

// DisplaySettingsContainsFold applies the ContainsFold predicate on the "display_settings" field.
func DisplaySettingsContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldDisplaySettings, v))
}

// CustomFieldsEQ applies the EQ predicate on the "custom_fields" field.
func CustomFieldsEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCustomFields, v))
}

// CustomFieldsNEQ applies the NEQ predicate on the "custom_fields" field.
func CustomFieldsNEQ(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldCustomFields, v))
}

// CustomFieldsIn applies the In predicate on the "custom_fields" field.
func CustomFieldsIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldCustomFields, vs...))
}

// CustomFieldsNotIn applies the NotIn predicate on the "custom_fields" field.
func CustomFieldsNotIn(vs ...string) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldCustomFields, vs...))
}

// CustomFieldsGT applies the GT predicate on the "custom_fields" field.
func CustomFieldsGT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldCustomFields, v))
}

// CustomFieldsGTE applies the GTE predicate on the "custom_fields" field.
func CustomFieldsGTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldCustomFields, v))
}

// CustomFieldsLT applies the LT predicate on the "custom_fields" field.
func CustomFieldsLT(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldCustomFields, v))
}

// CustomFieldsLTE applies the LTE predicate on the "custom_fields" field.
func CustomFieldsLTE(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldCustomFields, v))
}

// CustomFieldsContains applies the Contains predicate on the "custom_fields" field.
func CustomFieldsContains(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContains(FieldCustomFields, v))
}

// CustomFieldsHasPrefix applies the HasPrefix predicate on the "custom_fields" field.
func CustomFieldsHasPrefix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasPrefix(FieldCustomFields, v))
}

// CustomFieldsHasSuffix applies the HasSuffix predicate on the "custom_fields" field.
func CustomFieldsHasSuffix(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldHasSuffix(FieldCustomFields, v))
}

// CustomFieldsEqualFold applies the EqualFold predicate on the "custom_fields" field.
func CustomFieldsEqualFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldEqualFold(FieldCustomFields, v))
}

// CustomFieldsContainsFold applies the ContainsFold predicate on the "custom_fields" field.
func CustomFieldsContainsFold(v string) predicate.Invoice {
	return predicate.Invoice(sql.FieldContainsFold(FieldCustomFields, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Invoice {
	return predicate.Invoice(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Invoice) predicate.Invoice {
	return predicate.Invoice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Invoice) predicate.Invoice {
	return predicate.Invoice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Invoice) predicate.Invoice {
	return predicate.Invoice(sql.NotPredicates(p))
}
