// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MartialM1nd/freefsm/internal/ent/customercontact"
	"github.com/MartialM1nd/freefsm/internal/ent/predicate"
)

// CustomerContactUpdate is the builder for updating CustomerContact entities.
type CustomerContactUpdate struct {
	config
	hooks    []Hook
	mutation *CustomerContactMutation
}

// Where appends a list predicates to the CustomerContactUpdate builder.
func (_u *CustomerContactUpdate) Where(ps ...predicate.CustomerContact) *CustomerContactUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCustomerID sets the "customer_id" field.
func (_u *CustomerContactUpdate) SetCustomerID(v int64) *CustomerContactUpdate {
	_u.mutation.ResetCustomerID()
	_u.mutation.SetCustomerID(v)
	return _u
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_u *CustomerContactUpdate) SetNillableCustomerID(v *int64) *CustomerContactUpdate {
	if v != nil {
		_u.SetCustomerID(*v)
	}
	return _u
}

// AddCustomerID adds value to the "customer_id" field.
func (_u *CustomerContactUpdate) AddCustomerID(v int64) *CustomerContactUpdate {
	_u.mutation.AddCustomerID(v)
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *CustomerContactUpdate) SetFirstName(v string) *CustomerContactUpdate {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *CustomerContactUpdate) SetNillableFirstName(v *string) *CustomerContactUpdate {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *CustomerContactUpdate) SetLastName(v string) *CustomerContactUpdate {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *CustomerContactUpdate) SetNillableLastName(v *string) *CustomerContactUpdate {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *CustomerContactUpdate) SetEmail(v string) *CustomerContactUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *CustomerContactUpdate) SetNillableEmail(v *string) *CustomerContactUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *CustomerContactUpdate) SetPhone(v string) *CustomerContactUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *CustomerContactUpdate) SetNillablePhone(v *string) *CustomerContactUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *CustomerContactUpdate) SetNotes(v string) *CustomerContactUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *CustomerContactUpdate) SetNillableNotes(v *string) *CustomerContactUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *CustomerContactUpdate) SetSortOrder(v int) *CustomerContactUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *CustomerContactUpdate) SetNillableSortOrder(v *int) *CustomerContactUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *CustomerContactUpdate) AddSortOrder(v int) *CustomerContactUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomerContactUpdate) SetUpdatedAt(v time.Time) *CustomerContactUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CustomerContactMutation object of the builder.
func (_u *CustomerContactUpdate) Mutation() *CustomerContactMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomerContactUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomerContactUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomerContactUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomerContactUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomerContactUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := customercontact.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CustomerContactUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(customercontact.Table, customercontact.Columns, sqlgraph.NewFieldSpec(customercontact.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CustomerID(); ok {
		_spec.SetField(customercontact.FieldCustomerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCustomerID(); ok {
		_spec.AddField(customercontact.FieldCustomerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(customercontact.FieldFirstName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(customercontact.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(customercontact.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(customercontact.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(customercontact.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(customercontact.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(customercontact.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customercontact.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customercontact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CustomerContactUpdateOne is the builder for updating a single CustomerContact entity.
type CustomerContactUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CustomerContactMutation
}

// SetCustomerID sets the "customer_id" field.
func (_u *CustomerContactUpdateOne) SetCustomerID(v int64) *CustomerContactUpdateOne {
	_u.mutation.ResetCustomerID()
	_u.mutation.SetCustomerID(v)
	return _u
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_u *CustomerContactUpdateOne) SetNillableCustomerID(v *int64) *CustomerContactUpdateOne {
	if v != nil {
		_u.SetCustomerID(*v)
	}
	return _u
}

// AddCustomerID adds value to the "customer_id" field.
func (_u *CustomerContactUpdateOne) AddCustomerID(v int64) *CustomerContactUpdateOne {
	_u.mutation.AddCustomerID(v)
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *CustomerContactUpdateOne) SetFirstName(v string) *CustomerContactUpdateOne {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *CustomerContactUpdateOne) SetNillableFirstName(v *string) *CustomerContactUpdateOne {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *CustomerContactUpdateOne) SetLastName(v string) *CustomerContactUpdateOne {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *CustomerContactUpdateOne) SetNillableLastName(v *string) *CustomerContactUpdateOne {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *CustomerContactUpdateOne) SetEmail(v string) *CustomerContactUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *CustomerContactUpdateOne) SetNillableEmail(v *string) *CustomerContactUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *CustomerContactUpdateOne) SetPhone(v string) *CustomerContactUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *CustomerContactUpdateOne) SetNillablePhone(v *string) *CustomerContactUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *CustomerContactUpdateOne) SetNotes(v string) *CustomerContactUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *CustomerContactUpdateOne) SetNillableNotes(v *string) *CustomerContactUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *CustomerContactUpdateOne) SetSortOrder(v int) *CustomerContactUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *CustomerContactUpdateOne) SetNillableSortOrder(v *int) *CustomerContactUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *CustomerContactUpdateOne) AddSortOrder(v int) *CustomerContactUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomerContactUpdateOne) SetUpdatedAt(v time.Time) *CustomerContactUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CustomerContactMutation object of the builder.
func (_u *CustomerContactUpdateOne) Mutation() *CustomerContactMutation {
	return _u.mutation
}

// Where appends a list predicates to the CustomerContactUpdate builder.
func (_u *CustomerContactUpdateOne) Where(ps ...predicate.CustomerContact) *CustomerContactUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CustomerContactUpdateOne) Select(field string, fields ...string) *CustomerContactUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CustomerContact entity.
func (_u *CustomerContactUpdateOne) Save(ctx context.Context) (*CustomerContact, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomerContactUpdateOne) SaveX(ctx context.Context) *CustomerContact {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomerContactUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomerContactUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomerContactUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := customercontact.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CustomerContactUpdateOne) sqlSave(ctx context.Context) (_node *CustomerContact, err error) {
	_spec := sqlgraph.NewUpdateSpec(customercontact.Table, customercontact.Columns, sqlgraph.NewFieldSpec(customercontact.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CustomerContact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, customercontact.FieldID)
		for _, f := range fields {
			if !customercontact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != customercontact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CustomerID(); ok {
		_spec.SetField(customercontact.FieldCustomerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCustomerID(); ok {
		_spec.AddField(customercontact.FieldCustomerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(customercontact.FieldFirstName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(customercontact.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(customercontact.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(customercontact.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(customercontact.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(customercontact.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(customercontact.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customercontact.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CustomerContact{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customercontact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
