// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/freefsm-project/freefsm/internal/ent/dashboardlayout"
	"github.com/freefsm-project/freefsm/internal/ent/predicate"
)

// DashboardLayoutDelete is the builder for deleting a DashboardLayout entity.
type DashboardLayoutDelete struct {
	config
	hooks    []Hook
	mutation *DashboardLayoutMutation
}

// Where appends a list predicates to the DashboardLayoutDelete builder.
func (_d *DashboardLayoutDelete) Where(ps ...predicate.DashboardLayout) *DashboardLayoutDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DashboardLayoutDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DashboardLayoutDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DashboardLayoutDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dashboardlayout.Table, sqlgraph.NewFieldSpec(dashboardlayout.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DashboardLayoutDeleteOne is the builder for deleting a single DashboardLayout entity.
type DashboardLayoutDeleteOne struct {
	_d *DashboardLayoutDelete
}

// Where appends a list predicates to the DashboardLayoutDelete builder.
func (_d *DashboardLayoutDeleteOne) Where(ps ...predicate.DashboardLayout) *DashboardLayoutDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DashboardLayoutDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dashboardlayout.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DashboardLayoutDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
