// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/freefsm-project/freefsm/internal/ent/dashboardwidget"
	"github.com/freefsm-project/freefsm/internal/ent/predicate"
)

// DashboardWidgetDelete is the builder for deleting a DashboardWidget entity.
type DashboardWidgetDelete struct {
	config
	hooks    []Hook
	mutation *DashboardWidgetMutation
}

// Where appends a list predicates to the DashboardWidgetDelete builder.
func (_d *DashboardWidgetDelete) Where(ps ...predicate.DashboardWidget) *DashboardWidgetDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DashboardWidgetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DashboardWidgetDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DashboardWidgetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dashboardwidget.Table, sqlgraph.NewFieldSpec(dashboardwidget.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DashboardWidgetDeleteOne is the builder for deleting a single DashboardWidget entity.
type DashboardWidgetDeleteOne struct {
	_d *DashboardWidgetDelete
}

// Where appends a list predicates to the DashboardWidgetDelete builder.
func (_d *DashboardWidgetDeleteOne) Where(ps ...predicate.DashboardWidget) *DashboardWidgetDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DashboardWidgetDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dashboardwidget.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DashboardWidgetDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
