// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/freefsm-project/freefsm/internal/ent/dashboardwidget"
)

// DashboardWidgetCreate is the builder for creating a DashboardWidget entity.
type DashboardWidgetCreate struct {
	config
	mutation *DashboardWidgetMutation
	hooks    []Hook
}

// SetLayoutID sets the "layout_id" field.
func (_c *DashboardWidgetCreate) SetLayoutID(v int64) *DashboardWidgetCreate {
	_c.mutation.SetLayoutID(v)
	return _c
}

// SetWidgetType sets the "widget_type" field.
func (_c *DashboardWidgetCreate) SetWidgetType(v string) *DashboardWidgetCreate {
	_c.mutation.SetWidgetType(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *DashboardWidgetCreate) SetTitle(v string) *DashboardWidgetCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *DashboardWidgetCreate) SetNillableTitle(v *string) *DashboardWidgetCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetPosition sets the "position" field.
func (_c *DashboardWidgetCreate) SetPosition(v int) *DashboardWidgetCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_c *DashboardWidgetCreate) SetNillablePosition(v *int) *DashboardWidgetCreate {
	if v != nil {
		_c.SetPosition(*v)
	}
	return _c
}

// SetHidden sets the "hidden" field.
func (_c *DashboardWidgetCreate) SetHidden(v bool) *DashboardWidgetCreate {
	_c.mutation.SetHidden(v)
	return _c
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (_c *DashboardWidgetCreate) SetNillableHidden(v *bool) *DashboardWidgetCreate {
	if v != nil {
		_c.SetHidden(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *DashboardWidgetCreate) SetConfig(v string) *DashboardWidgetCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_c *DashboardWidgetCreate) SetNillableConfig(v *string) *DashboardWidgetCreate {
	if v != nil {
		_c.SetConfig(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DashboardWidgetCreate) SetCreatedAt(v time.Time) *DashboardWidgetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DashboardWidgetCreate) SetNillableCreatedAt(v *time.Time) *DashboardWidgetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DashboardWidgetCreate) SetUpdatedAt(v time.Time) *DashboardWidgetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DashboardWidgetCreate) SetNillableUpdatedAt(v *time.Time) *DashboardWidgetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DashboardWidgetCreate) SetID(v int64) *DashboardWidgetCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the DashboardWidgetMutation object of the builder.
func (_c *DashboardWidgetCreate) Mutation() *DashboardWidgetMutation {
	return _c.mutation
}

// Save creates the DashboardWidget in the database.
func (_c *DashboardWidgetCreate) Save(ctx context.Context) (*DashboardWidget, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DashboardWidgetCreate) SaveX(ctx context.Context) *DashboardWidget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DashboardWidgetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DashboardWidgetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DashboardWidgetCreate) defaults() {
	if _, ok := _c.mutation.Title(); !ok {
		v := dashboardwidget.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Position(); !ok {
		v := dashboardwidget.DefaultPosition
		_c.mutation.SetPosition(v)
	}
	if _, ok := _c.mutation.Hidden(); !ok {
		v := dashboardwidget.DefaultHidden
		_c.mutation.SetHidden(v)
	}
	if _, ok := _c.mutation.Config(); !ok {
		v := dashboardwidget.DefaultConfig
		_c.mutation.SetConfig(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dashboardwidget.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dashboardwidget.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DashboardWidgetCreate) check() error {
	if _, ok := _c.mutation.LayoutID(); !ok {
		return &ValidationError{Name: "layout_id", err: errors.New(`ent: missing required field "DashboardWidget.layout_id"`)}
	}
	if _, ok := _c.mutation.WidgetType(); !ok {
		return &ValidationError{Name: "widget_type", err: errors.New(`ent: missing required field "DashboardWidget.widget_type"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "DashboardWidget.title"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "DashboardWidget.position"`)}
	}
	if _, ok := _c.mutation.Hidden(); !ok {
		return &ValidationError{Name: "hidden", err: errors.New(`ent: missing required field "DashboardWidget.hidden"`)}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "DashboardWidget.config"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DashboardWidget.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DashboardWidget.updated_at"`)}
	}
	return nil
}

func (_c *DashboardWidgetCreate) sqlSave(ctx context.Context) (*DashboardWidget, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DashboardWidgetCreate) createSpec() (*DashboardWidget, *sqlgraph.CreateSpec) {
	var (
		_node = &DashboardWidget{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dashboardwidget.Table, sqlgraph.NewFieldSpec(dashboardwidget.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.LayoutID(); ok {
		_spec.SetField(dashboardwidget.FieldLayoutID, field.TypeInt64, value)
		_node.LayoutID = value
	}
	if value, ok := _c.mutation.WidgetType(); ok {
		_spec.SetField(dashboardwidget.FieldWidgetType, field.TypeString, value)
		_node.WidgetType = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(dashboardwidget.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(dashboardwidget.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.Hidden(); ok {
		_spec.SetField(dashboardwidget.FieldHidden, field.TypeBool, value)
		_node.Hidden = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(dashboardwidget.FieldConfig, field.TypeString, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dashboardwidget.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dashboardwidget.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DashboardWidgetCreateBulk is the builder for creating many DashboardWidget entities in bulk.
type DashboardWidgetCreateBulk struct {
	config
	err      error
	builders []*DashboardWidgetCreate
}

// Save creates the DashboardWidget entities in the database.
func (_c *DashboardWidgetCreateBulk) Save(ctx context.Context) ([]*DashboardWidget, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DashboardWidget, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DashboardWidgetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DashboardWidgetCreateBulk) SaveX(ctx context.Context) []*DashboardWidget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DashboardWidgetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DashboardWidgetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
