// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/freefsm-project/freefsm/internal/ent/location"
	"github.com/freefsm-project/freefsm/internal/ent/predicate"
)

// LocationUpdate is the builder for updating Location entities.
type LocationUpdate struct {
	config
	hooks    []Hook
	mutation *LocationMutation
}

// Where appends a list predicates to the LocationUpdate builder.
func (_u *LocationUpdate) Where(ps ...predicate.Location) *LocationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCompanyID sets the "company_id" field.
func (_u *LocationUpdate) SetCompanyID(v int64) *LocationUpdate {
	_u.mutation.ResetCompanyID()
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableCompanyID(v *int64) *LocationUpdate {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// AddCompanyID adds value to the "company_id" field.
func (_u *LocationUpdate) AddCompanyID(v int64) *LocationUpdate {
	_u.mutation.AddCompanyID(v)
	return _u
}

// ClearCompanyID clears the value of the "company_id" field.
func (_u *LocationUpdate) ClearCompanyID() *LocationUpdate {
	_u.mutation.ClearCompanyID()
	return _u
}

// SetObjectType sets the "object_type" field.
func (_u *LocationUpdate) SetObjectType(v string) *LocationUpdate {
	_u.mutation.SetObjectType(v)
	return _u
}

// SetNillableObjectType sets the "object_type" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableObjectType(v *string) *LocationUpdate {
	if v != nil {
		_u.SetObjectType(*v)
	}
	return _u
}

// SetObjectID sets the "object_id" field.
func (_u *LocationUpdate) SetObjectID(v int64) *LocationUpdate {
	_u.mutation.ResetObjectID()
	_u.mutation.SetObjectID(v)
	return _u
}

// SetNillableObjectID sets the "object_id" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableObjectID(v *int64) *LocationUpdate {
	if v != nil {
		_u.SetObjectID(*v)
	}
	return _u
}

// AddObjectID adds value to the "object_id" field.
func (_u *LocationUpdate) AddObjectID(v int64) *LocationUpdate {
	_u.mutation.AddObjectID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *LocationUpdate) SetTitle(v string) *LocationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableTitle(v *string) *LocationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAddress1 sets the "address_1" field.
func (_u *LocationUpdate) SetAddress1(v string) *LocationUpdate {
	_u.mutation.SetAddress1(v)
	return _u
}

// SetNillableAddress1 sets the "address_1" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableAddress1(v *string) *LocationUpdate {
	if v != nil {
		_u.SetAddress1(*v)
	}
	return _u
}

// SetAddress2 sets the "address_2" field.
func (_u *LocationUpdate) SetAddress2(v string) *LocationUpdate {
	_u.mutation.SetAddress2(v)
	return _u
}

// SetNillableAddress2 sets the "address_2" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableAddress2(v *string) *LocationUpdate {
	if v != nil {
		_u.SetAddress2(*v)
	}
	return _u
}

// SetCity sets the "city" field.
func (_u *LocationUpdate) SetCity(v string) *LocationUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableCity(v *string) *LocationUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *LocationUpdate) SetState(v string) *LocationUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableState(v *string) *LocationUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetZipCode sets the "zip_code" field.
func (_u *LocationUpdate) SetZipCode(v string) *LocationUpdate {
	_u.mutation.SetZipCode(v)
	return _u
}

// SetNillableZipCode sets the "zip_code" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableZipCode(v *string) *LocationUpdate {
	if v != nil {
		_u.SetZipCode(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *LocationUpdate) SetNotes(v string) *LocationUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableNotes(v *string) *LocationUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *LocationUpdate) SetLatitude(v float64) *LocationUpdate {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableLatitude(v *float64) *LocationUpdate {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *LocationUpdate) AddLatitude(v float64) *LocationUpdate {
	_u.mutation.AddLatitude(v)
	return _u
}

// ClearLatitude clears the value of the "latitude" field.
func (_u *LocationUpdate) ClearLatitude() *LocationUpdate {
	_u.mutation.ClearLatitude()
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *LocationUpdate) SetLongitude(v float64) *LocationUpdate {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableLongitude(v *float64) *LocationUpdate {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *LocationUpdate) AddLongitude(v float64) *LocationUpdate {
	_u.mutation.AddLongitude(v)
	return _u
}

// ClearLongitude clears the value of the "longitude" field.
func (_u *LocationUpdate) ClearLongitude() *LocationUpdate {
	_u.mutation.ClearLongitude()
	return _u
}

// SetGeocodedAt sets the "geocoded_at" field.
func (_u *LocationUpdate) SetGeocodedAt(v time.Time) *LocationUpdate {
	_u.mutation.SetGeocodedAt(v)
	return _u
}

// SetNillableGeocodedAt sets the "geocoded_at" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableGeocodedAt(v *time.Time) *LocationUpdate {
	if v != nil {
		_u.SetGeocodedAt(*v)
	}
	return _u
}

// ClearGeocodedAt clears the value of the "geocoded_at" field.
func (_u *LocationUpdate) ClearGeocodedAt() *LocationUpdate {
	_u.mutation.ClearGeocodedAt()
	return _u
}

// SetGeocodeSource sets the "geocode_source" field.
func (_u *LocationUpdate) SetGeocodeSource(v string) *LocationUpdate {
	_u.mutation.SetGeocodeSource(v)
	return _u
}

// SetNillableGeocodeSource sets the "geocode_source" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableGeocodeSource(v *string) *LocationUpdate {
	if v != nil {
		_u.SetGeocodeSource(*v)
	}
	return _u
}

// ClearGeocodeSource clears the value of the "geocode_source" field.
func (_u *LocationUpdate) ClearGeocodeSource() *LocationUpdate {
	_u.mutation.ClearGeocodeSource()
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *LocationUpdate) SetIsPrimary(v bool) *LocationUpdate {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *LocationUpdate) SetNillableIsPrimary(v *bool) *LocationUpdate {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LocationUpdate) SetUpdatedAt(v time.Time) *LocationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the LocationMutation object of the builder.
func (_u *LocationUpdate) Mutation() *LocationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LocationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LocationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LocationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LocationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LocationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := location.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *LocationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(location.Table, location.Columns, sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyID(); ok {
		_spec.SetField(location.FieldCompanyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCompanyID(); ok {
		_spec.AddField(location.FieldCompanyID, field.TypeInt64, value)
	}
	if _u.mutation.CompanyIDCleared() {
		_spec.ClearField(location.FieldCompanyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ObjectType(); ok {
		_spec.SetField(location.FieldObjectType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectID(); ok {
		_spec.SetField(location.FieldObjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedObjectID(); ok {
		_spec.AddField(location.FieldObjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(location.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address1(); ok {
		_spec.SetField(location.FieldAddress1, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address2(); ok {
		_spec.SetField(location.FieldAddress2, field.TypeString, value)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(location.FieldCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(location.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ZipCode(); ok {
		_spec.SetField(location.FieldZipCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(location.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(location.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(location.FieldLatitude, field.TypeFloat64, value)
	}
	if _u.mutation.LatitudeCleared() {
		_spec.ClearField(location.FieldLatitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(location.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(location.FieldLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.LongitudeCleared() {
		_spec.ClearField(location.FieldLongitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.GeocodedAt(); ok {
		_spec.SetField(location.FieldGeocodedAt, field.TypeTime, value)
	}
	if _u.mutation.GeocodedAtCleared() {
		_spec.ClearField(location.FieldGeocodedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GeocodeSource(); ok {
		_spec.SetField(location.FieldGeocodeSource, field.TypeString, value)
	}
	if _u.mutation.GeocodeSourceCleared() {
		_spec.ClearField(location.FieldGeocodeSource, field.TypeString)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(location.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(location.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{location.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LocationUpdateOne is the builder for updating a single Location entity.
type LocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LocationMutation
}

// SetCompanyID sets the "company_id" field.
func (_u *LocationUpdateOne) SetCompanyID(v int64) *LocationUpdateOne {
	_u.mutation.ResetCompanyID()
	_u.mutation.SetCompanyID(v)
	return _u
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableCompanyID(v *int64) *LocationUpdateOne {
	if v != nil {
		_u.SetCompanyID(*v)
	}
	return _u
}

// AddCompanyID adds value to the "company_id" field.
func (_u *LocationUpdateOne) AddCompanyID(v int64) *LocationUpdateOne {
	_u.mutation.AddCompanyID(v)
	return _u
}

// ClearCompanyID clears the value of the "company_id" field.
func (_u *LocationUpdateOne) ClearCompanyID() *LocationUpdateOne {
	_u.mutation.ClearCompanyID()
	return _u
}

// SetObjectType sets the "object_type" field.
func (_u *LocationUpdateOne) SetObjectType(v string) *LocationUpdateOne {
	_u.mutation.SetObjectType(v)
	return _u
}

// SetNillableObjectType sets the "object_type" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableObjectType(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetObjectType(*v)
	}
	return _u
}

// SetObjectID sets the "object_id" field.
func (_u *LocationUpdateOne) SetObjectID(v int64) *LocationUpdateOne {
	_u.mutation.ResetObjectID()
	_u.mutation.SetObjectID(v)
	return _u
}

// SetNillableObjectID sets the "object_id" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableObjectID(v *int64) *LocationUpdateOne {
	if v != nil {
		_u.SetObjectID(*v)
	}
	return _u
}

// AddObjectID adds value to the "object_id" field.
func (_u *LocationUpdateOne) AddObjectID(v int64) *LocationUpdateOne {
	_u.mutation.AddObjectID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *LocationUpdateOne) SetTitle(v string) *LocationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableTitle(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAddress1 sets the "address_1" field.
func (_u *LocationUpdateOne) SetAddress1(v string) *LocationUpdateOne {
	_u.mutation.SetAddress1(v)
	return _u
}

// SetNillableAddress1 sets the "address_1" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableAddress1(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetAddress1(*v)
	}
	return _u
}

// SetAddress2 sets the "address_2" field.
func (_u *LocationUpdateOne) SetAddress2(v string) *LocationUpdateOne {
	_u.mutation.SetAddress2(v)
	return _u
}

// SetNillableAddress2 sets the "address_2" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableAddress2(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetAddress2(*v)
	}
	return _u
}

// SetCity sets the "city" field.
func (_u *LocationUpdateOne) SetCity(v string) *LocationUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableCity(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *LocationUpdateOne) SetState(v string) *LocationUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableState(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetZipCode sets the "zip_code" field.
func (_u *LocationUpdateOne) SetZipCode(v string) *LocationUpdateOne {
	_u.mutation.SetZipCode(v)
	return _u
}

// SetNillableZipCode sets the "zip_code" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableZipCode(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetZipCode(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *LocationUpdateOne) SetNotes(v string) *LocationUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableNotes(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetLatitude sets the "latitude" field.
func (_u *LocationUpdateOne) SetLatitude(v float64) *LocationUpdateOne {
	_u.mutation.ResetLatitude()
	_u.mutation.SetLatitude(v)
	return _u
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableLatitude(v *float64) *LocationUpdateOne {
	if v != nil {
		_u.SetLatitude(*v)
	}
	return _u
}

// AddLatitude adds value to the "latitude" field.
func (_u *LocationUpdateOne) AddLatitude(v float64) *LocationUpdateOne {
	_u.mutation.AddLatitude(v)
	return _u
}

// ClearLatitude clears the value of the "latitude" field.
func (_u *LocationUpdateOne) ClearLatitude() *LocationUpdateOne {
	_u.mutation.ClearLatitude()
	return _u
}

// SetLongitude sets the "longitude" field.
func (_u *LocationUpdateOne) SetLongitude(v float64) *LocationUpdateOne {
	_u.mutation.ResetLongitude()
	_u.mutation.SetLongitude(v)
	return _u
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableLongitude(v *float64) *LocationUpdateOne {
	if v != nil {
		_u.SetLongitude(*v)
	}
	return _u
}

// AddLongitude adds value to the "longitude" field.
func (_u *LocationUpdateOne) AddLongitude(v float64) *LocationUpdateOne {
	_u.mutation.AddLongitude(v)
	return _u
}

// ClearLongitude clears the value of the "longitude" field.
func (_u *LocationUpdateOne) ClearLongitude() *LocationUpdateOne {
	_u.mutation.ClearLongitude()
	return _u
}

// SetGeocodedAt sets the "geocoded_at" field.
func (_u *LocationUpdateOne) SetGeocodedAt(v time.Time) *LocationUpdateOne {
	_u.mutation.SetGeocodedAt(v)
	return _u
}

// SetNillableGeocodedAt sets the "geocoded_at" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableGeocodedAt(v *time.Time) *LocationUpdateOne {
	if v != nil {
		_u.SetGeocodedAt(*v)
	}
	return _u
}

// ClearGeocodedAt clears the value of the "geocoded_at" field.
func (_u *LocationUpdateOne) ClearGeocodedAt() *LocationUpdateOne {
	_u.mutation.ClearGeocodedAt()
	return _u
}

// SetGeocodeSource sets the "geocode_source" field.
func (_u *LocationUpdateOne) SetGeocodeSource(v string) *LocationUpdateOne {
	_u.mutation.SetGeocodeSource(v)
	return _u
}

// SetNillableGeocodeSource sets the "geocode_source" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableGeocodeSource(v *string) *LocationUpdateOne {
	if v != nil {
		_u.SetGeocodeSource(*v)
	}
	return _u
}

// ClearGeocodeSource clears the value of the "geocode_source" field.
func (_u *LocationUpdateOne) ClearGeocodeSource() *LocationUpdateOne {
	_u.mutation.ClearGeocodeSource()
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *LocationUpdateOne) SetIsPrimary(v bool) *LocationUpdateOne {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *LocationUpdateOne) SetNillableIsPrimary(v *bool) *LocationUpdateOne {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LocationUpdateOne) SetUpdatedAt(v time.Time) *LocationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the LocationMutation object of the builder.
func (_u *LocationUpdateOne) Mutation() *LocationMutation {
	return _u.mutation
}

// Where appends a list predicates to the LocationUpdate builder.
func (_u *LocationUpdateOne) Where(ps ...predicate.Location) *LocationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LocationUpdateOne) Select(field string, fields ...string) *LocationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Location entity.
func (_u *LocationUpdateOne) Save(ctx context.Context) (*Location, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LocationUpdateOne) SaveX(ctx context.Context) *Location {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LocationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LocationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LocationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := location.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *LocationUpdateOne) sqlSave(ctx context.Context) (_node *Location, err error) {
	_spec := sqlgraph.NewUpdateSpec(location.Table, location.Columns, sqlgraph.NewFieldSpec(location.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Location.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, location.FieldID)
		for _, f := range fields {
			if !location.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != location.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyID(); ok {
		_spec.SetField(location.FieldCompanyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCompanyID(); ok {
		_spec.AddField(location.FieldCompanyID, field.TypeInt64, value)
	}
	if _u.mutation.CompanyIDCleared() {
		_spec.ClearField(location.FieldCompanyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ObjectType(); ok {
		_spec.SetField(location.FieldObjectType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectID(); ok {
		_spec.SetField(location.FieldObjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedObjectID(); ok {
		_spec.AddField(location.FieldObjectID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(location.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address1(); ok {
		_spec.SetField(location.FieldAddress1, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address2(); ok {
		_spec.SetField(location.FieldAddress2, field.TypeString, value)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(location.FieldCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(location.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ZipCode(); ok {
		_spec.SetField(location.FieldZipCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(location.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.Latitude(); ok {
		_spec.SetField(location.FieldLatitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLatitude(); ok {
		_spec.AddField(location.FieldLatitude, field.TypeFloat64, value)
	}
	if _u.mutation.LatitudeCleared() {
		_spec.ClearField(location.FieldLatitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Longitude(); ok {
		_spec.SetField(location.FieldLongitude, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLongitude(); ok {
		_spec.AddField(location.FieldLongitude, field.TypeFloat64, value)
	}
	if _u.mutation.LongitudeCleared() {
		_spec.ClearField(location.FieldLongitude, field.TypeFloat64)
	}
	if value, ok := _u.mutation.GeocodedAt(); ok {
		_spec.SetField(location.FieldGeocodedAt, field.TypeTime, value)
	}
	if _u.mutation.GeocodedAtCleared() {
		_spec.ClearField(location.FieldGeocodedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.GeocodeSource(); ok {
		_spec.SetField(location.FieldGeocodeSource, field.TypeString, value)
	}
	if _u.mutation.GeocodeSourceCleared() {
		_spec.ClearField(location.FieldGeocodeSource, field.TypeString)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(location.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(location.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Location{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{location.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
