// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MartialM1nd/freefsm/internal/ent/statusworkflow"
)

// StatusWorkflowCreate is the builder for creating a StatusWorkflow entity.
type StatusWorkflowCreate struct {
	config
	mutation *StatusWorkflowMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *StatusWorkflowCreate) SetName(v string) *StatusWorkflowCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetObjectType sets the "object_type" field.
func (_c *StatusWorkflowCreate) SetObjectType(v string) *StatusWorkflowCreate {
	_c.mutation.SetObjectType(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StatusWorkflowCreate) SetCreatedAt(v time.Time) *StatusWorkflowCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *StatusWorkflowCreate) SetID(v int64) *StatusWorkflowCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the StatusWorkflowMutation object of the builder.
func (_c *StatusWorkflowCreate) Mutation() *StatusWorkflowMutation {
	return _c.mutation
}

// Save creates the StatusWorkflow in the database.
func (_c *StatusWorkflowCreate) Save(ctx context.Context) (*StatusWorkflow, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StatusWorkflowCreate) SaveX(ctx context.Context) *StatusWorkflow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StatusWorkflowCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StatusWorkflowCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StatusWorkflowCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "StatusWorkflow.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := statusworkflow.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StatusWorkflow.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ObjectType(); !ok {
		return &ValidationError{Name: "object_type", err: errors.New(`ent: missing required field "StatusWorkflow.object_type"`)}
	}
	if v, ok := _c.mutation.ObjectType(); ok {
		if err := statusworkflow.ObjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "object_type", err: fmt.Errorf(`ent: validator failed for field "StatusWorkflow.object_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StatusWorkflow.created_at"`)}
	}
	return nil
}

func (_c *StatusWorkflowCreate) sqlSave(ctx context.Context) (*StatusWorkflow, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StatusWorkflowCreate) createSpec() (*StatusWorkflow, *sqlgraph.CreateSpec) {
	var (
		_node = &StatusWorkflow{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(statusworkflow.Table, sqlgraph.NewFieldSpec(statusworkflow.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(statusworkflow.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ObjectType(); ok {
		_spec.SetField(statusworkflow.FieldObjectType, field.TypeString, value)
		_node.ObjectType = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(statusworkflow.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// StatusWorkflowCreateBulk is the builder for creating many StatusWorkflow entities in bulk.
type StatusWorkflowCreateBulk struct {
	config
	err      error
	builders []*StatusWorkflowCreate
}

// Save creates the StatusWorkflow entities in the database.
func (_c *StatusWorkflowCreateBulk) Save(ctx context.Context) ([]*StatusWorkflow, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StatusWorkflow, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StatusWorkflowMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StatusWorkflowCreateBulk) SaveX(ctx context.Context) []*StatusWorkflow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StatusWorkflowCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StatusWorkflowCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
