// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/MartialM1nd/freefsm/internal/ent/timeentry"
)

// TimeEntry is the model entity for the TimeEntry schema.
type TimeEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// IsManual holds the value of the "is_manual" field.
	IsManual bool `json:"is_manual,omitempty"`
	// ClockIn holds the value of the "clock_in" field.
	ClockIn time.Time `json:"clock_in,omitempty"`
	// ClockOut holds the value of the "clock_out" field.
	ClockOut *time.Time `json:"clock_out,omitempty"`
	// Latitude holds the value of the "latitude" field.
	Latitude *float64 `json:"latitude,omitempty"`
	// Longitude holds the value of the "longitude" field.
	Longitude *float64 `json:"longitude,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TimeEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case timeentry.FieldIsManual:
			values[i] = new(sql.NullBool)
		case timeentry.FieldLatitude, timeentry.FieldLongitude:
			values[i] = new(sql.NullFloat64)
		case timeentry.FieldID, timeentry.FieldUserID:
			values[i] = new(sql.NullInt64)
		case timeentry.FieldNotes:
			values[i] = new(sql.NullString)
		case timeentry.FieldClockIn, timeentry.FieldClockOut, timeentry.FieldCreatedAt, timeentry.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TimeEntry fields.
func (_m *TimeEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case timeentry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case timeentry.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case timeentry.FieldIsManual:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_manual", values[i])
			} else if value.Valid {
				_m.IsManual = value.Bool
			}
		case timeentry.FieldClockIn:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field clock_in", values[i])
			} else if value.Valid {
				_m.ClockIn = value.Time
			}
		case timeentry.FieldClockOut:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field clock_out", values[i])
			} else if value.Valid {
				_m.ClockOut = new(time.Time)
				*_m.ClockOut = value.Time
			}
		case timeentry.FieldLatitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field latitude", values[i])
			} else if value.Valid {
				_m.Latitude = new(float64)
				*_m.Latitude = value.Float64
			}
		case timeentry.FieldLongitude:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field longitude", values[i])
			} else if value.Valid {
				_m.Longitude = new(float64)
				*_m.Longitude = value.Float64
			}
		case timeentry.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case timeentry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case timeentry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TimeEntry.
// This includes values selected through modifiers, order, etc.
func (_m *TimeEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TimeEntry.
// Note that you need to call TimeEntry.Unwrap() before calling this method if this TimeEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TimeEntry) Update() *TimeEntryUpdateOne {
	return NewTimeEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TimeEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TimeEntry) Unwrap() *TimeEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TimeEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TimeEntry) String() string {
	var builder strings.Builder
	builder.WriteString("TimeEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("is_manual=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsManual))
	builder.WriteString(", ")
	builder.WriteString("clock_in=")
	builder.WriteString(_m.ClockIn.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ClockOut; v != nil {
		builder.WriteString("clock_out=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.Latitude; v != nil {
		builder.WriteString("latitude=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Longitude; v != nil {
		builder.WriteString("longitude=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TimeEntries is a parsable slice of TimeEntry.
type TimeEntries []*TimeEntry
