// Code generated by ent, DO NOT EDIT.

package companysettings

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the companysettings type in the database.
	Label = "company_settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBusinessName holds the string denoting the business_name field in the database.
	FieldBusinessName = "business_name"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldCity holds the string denoting the city field in the database.
	FieldCity = "city"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldZip holds the string denoting the zip field in the database.
	FieldZip = "zip"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldTaxID holds the string denoting the tax_id field in the database.
	FieldTaxID = "tax_id"
	// FieldDefaultTaxRate holds the string denoting the default_tax_rate field in the database.
	FieldDefaultTaxRate = "default_tax_rate"
	// FieldInvoicePrefix holds the string denoting the invoice_prefix field in the database.
	FieldInvoicePrefix = "invoice_prefix"
	// FieldEstimatePrefix holds the string denoting the estimate_prefix field in the database.
	FieldEstimatePrefix = "estimate_prefix"
	// FieldDefaultDueDays holds the string denoting the default_due_days field in the database.
	FieldDefaultDueDays = "default_due_days"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the companysettings in the database.
	Table = "company_settings"
)

// Columns holds all SQL columns for companysettings fields.
var Columns = []string{
	FieldID,
	FieldBusinessName,
	FieldAddress,
	FieldCity,
	FieldState,
	FieldZip,
	FieldPhone,
	FieldEmail,
	FieldTaxID,
	FieldDefaultTaxRate,
	FieldInvoicePrefix,
	FieldEstimatePrefix,
	FieldDefaultDueDays,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBusinessName holds the default value on creation for the "business_name" field.
	DefaultBusinessName string
	// DefaultAddress holds the default value on creation for the "address" field.
	DefaultAddress string
	// DefaultCity holds the default value on creation for the "city" field.
	DefaultCity string
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState string
	// DefaultZip holds the default value on creation for the "zip" field.
	DefaultZip string
	// DefaultPhone holds the default value on creation for the "phone" field.
	DefaultPhone string
	// DefaultEmail holds the default value on creation for the "email" field.
	DefaultEmail string
	// DefaultTaxID holds the default value on creation for the "tax_id" field.
	DefaultTaxID string
	// DefaultDefaultTaxRate holds the default value on creation for the "default_tax_rate" field.
	DefaultDefaultTaxRate string
	// DefaultInvoicePrefix holds the default value on creation for the "invoice_prefix" field.
	DefaultInvoicePrefix string
	// DefaultEstimatePrefix holds the default value on creation for the "estimate_prefix" field.
	DefaultEstimatePrefix string
	// DefaultDefaultDueDays holds the default value on creation for the "default_due_days" field.
	DefaultDefaultDueDays int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CompanySettings queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBusinessName orders the results by the business_name field.
func ByBusinessName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBusinessName, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByCity orders the results by the city field.
func ByCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCity, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByZip orders the results by the zip field.
func ByZip(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldZip, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByTaxID orders the results by the tax_id field.
func ByTaxID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxID, opts...).ToFunc()
}

// ByDefaultTaxRate orders the results by the default_tax_rate field.
func ByDefaultTaxRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultTaxRate, opts...).ToFunc()
}

// ByInvoicePrefix orders the results by the invoice_prefix field.
func ByInvoicePrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoicePrefix, opts...).ToFunc()
}

// ByEstimatePrefix orders the results by the estimate_prefix field.
func ByEstimatePrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatePrefix, opts...).ToFunc()
}

// ByDefaultDueDays orders the results by the default_due_days field.
func ByDefaultDueDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultDueDays, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
