DROP TRIGGER IF EXISTS hidden_invoice_application_guard ON credit_applications;
DROP TRIGGER IF EXISTS hidden_invoice_allocation_guard ON payment_invoice_allocations;
DROP TRIGGER IF EXISTS hidden_invoice_payment_guard ON invoice_payments;
DROP FUNCTION IF EXISTS guard_hidden_invoice_settlement();
DROP TRIGGER IF EXISTS conversion_cycle_immutable ON estimate_invoice_conversion_cycles;
DROP FUNCTION IF EXISTS guard_conversion_cycle();
DROP TRIGGER IF EXISTS invoice_conversion_tombstone_guard ON invoices;
DROP TRIGGER IF EXISTS estimate_conversion_tombstone_guard ON estimates;
DROP FUNCTION IF EXISTS guard_invoice_conversion_tombstone();
DROP FUNCTION IF EXISTS guard_estimate_conversion_tombstone();
DROP TABLE IF EXISTS estimate_invoice_conversion_operations;
DROP TABLE IF EXISTS estimate_invoice_conversion_cycles;
DROP TRIGGER IF EXISTS invoice_status_ownership ON invoices;
DROP TRIGGER IF EXISTS estimate_status_ownership ON estimates;
DROP FUNCTION IF EXISTS validate_document_status_ownership();
DROP INDEX IF EXISTS invoices_normal_idx; DROP INDEX IF EXISTS estimates_normal_idx;
ALTER TABLE invoices DROP CONSTRAINT IF EXISTS invoices_id_company_unique;
ALTER TABLE estimates DROP CONSTRAINT IF EXISTS estimates_id_company_unique;
ALTER TABLE invoices DROP COLUMN IF EXISTS conversion_hidden_at;
ALTER TABLE estimates DROP COLUMN IF EXISTS conversion_hidden_at;
DROP INDEX IF EXISTS custom_field_conversion_key_unique;
DROP TRIGGER IF EXISTS custom_field_conversion_pair_guard ON custom_field_definitions;
DROP FUNCTION IF EXISTS validate_custom_field_conversion_pair();
ALTER TABLE custom_field_definitions DROP CONSTRAINT IF EXISTS custom_field_conversion_key_valid;
ALTER TABLE custom_field_definitions DROP COLUMN IF EXISTS conversion_key;
DROP INDEX IF EXISTS statuses_one_document_role_per_workflow;
DROP TRIGGER IF EXISTS status_conversion_capabilities ON statuses;
DROP FUNCTION IF EXISTS validate_status_conversion_capabilities();
ALTER TABLE statuses DROP COLUMN IF EXISTS document_role;
ALTER TABLE statuses DROP COLUMN IF EXISTS estimate_convertible;
ALTER TABLE statuses DROP CONSTRAINT IF EXISTS statuses_workflow_company_fk;
ALTER TABLE status_workflows DROP CONSTRAINT IF EXISTS status_workflows_id_company_unique;
ALTER TABLE activity_logs ALTER COLUMN company_id DROP NOT NULL;
ALTER TABLE comments ALTER COLUMN company_id DROP NOT NULL;
ALTER TABLE tag_links ALTER COLUMN company_id DROP NOT NULL;
ALTER TABLE files ALTER COLUMN company_id DROP NOT NULL;
