#!/bin/sh
#
# PROVIDE: freefsm
# REQUIRE: LOGIN postgresql
# KEYWORD: shutdown

. /etc/rc.subr

name="freefsm"
rcvar="freefsm_enable"

load_rc_config "$name"

: ${freefsm_enable:="NO"}
: ${freefsm_user:="freefsm"}

pidfile="/var/run/freefsm.pid"
procname="/usr/local/bin/freefsm"

start_cmd="freefsm_start"

freefsm_start() {
    echo "Starting ${name}."
    /usr/sbin/daemon -P ${pidfile} -u ${freefsm_user} \
        -o /var/log/freefsm/freefsm.log \
        ${procname} -config /usr/local/etc/freefsm.conf
}

run_rc_command "$1"
