#!/bin/sh

# PROVIDE: freefsm
# REQUIRE: LOGIN postgresql
# KEYWORD: shutdown

. /etc/rc.subr

name="freefsm"
rcvar="freefsm_enable"

command="/usr/local/bin/freefsm"
command_args="-config /usr/local/etc/freefsm.conf"
pidfile="/var/run/freefsm.pid"

load_rc_config "$name"

: ${freefsm_enable:="NO"}

run_rc_command "$1"
