#!/bin/sh

# PROVIDE: freefsm
# REQUIRE: LOGIN postgresql
# KEYWORD: shutdown

. /etc/rc.subr

name="freefsm"
rcvar="freefsm_enable"

load_rc_config "$name"

: ${freefsm_enable:="NO"}
: ${freefsm_user:="freefsm"}
: ${freefsm_group:="freefsm"}

pidfile="/var/run/${name}.pid"
command="/usr/local/bin/freefsm"
command_args="-config /usr/local/etc/${name}.conf"
freefsm_user="${freefsm_user}"

run_rc_command "$1"
