// Code generated by ent, DO NOT EDIT.

package customfielddefinition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/freefsm-project/freefsm/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLTE(FieldID, id))
}

// CompanyID applies equality check predicate on the "company_id" field. It's identical to CompanyIDEQ.
func CompanyID(v int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldCompanyID, v))
}

// ObjectType applies equality check predicate on the "object_type" field. It's identical to ObjectTypeEQ.
func ObjectType(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldObjectType, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldName, v))
}

// ConversionKey applies equality check predicate on the "conversion_key" field. It's identical to ConversionKeyEQ.
func ConversionKey(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldConversionKey, v))
}

// FieldType applies equality check predicate on the "field_type" field. It's identical to FieldTypeEQ.
func FieldType(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldFieldType, v))
}

// Required applies equality check predicate on the "required" field. It's identical to RequiredEQ.
func Required(v bool) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldRequired, v))
}

// Options applies equality check predicate on the "options" field. It's identical to OptionsEQ.
func Options(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldOptions, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompanyIDEQ applies the EQ predicate on the "company_id" field.
func CompanyIDEQ(v int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldCompanyID, v))
}

// CompanyIDNEQ applies the NEQ predicate on the "company_id" field.
func CompanyIDNEQ(v int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNEQ(FieldCompanyID, v))
}

// CompanyIDIn applies the In predicate on the "company_id" field.
func CompanyIDIn(vs ...int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldIn(FieldCompanyID, vs...))
}

// CompanyIDNotIn applies the NotIn predicate on the "company_id" field.
func CompanyIDNotIn(vs ...int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNotIn(FieldCompanyID, vs...))
}

// CompanyIDGT applies the GT predicate on the "company_id" field.
func CompanyIDGT(v int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGT(FieldCompanyID, v))
}

// CompanyIDGTE applies the GTE predicate on the "company_id" field.
func CompanyIDGTE(v int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGTE(FieldCompanyID, v))
}

// CompanyIDLT applies the LT predicate on the "company_id" field.
func CompanyIDLT(v int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLT(FieldCompanyID, v))
}

// CompanyIDLTE applies the LTE predicate on the "company_id" field.
func CompanyIDLTE(v int64) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLTE(FieldCompanyID, v))
}

// CompanyIDIsNil applies the IsNil predicate on the "company_id" field.
func CompanyIDIsNil() predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldIsNull(FieldCompanyID))
}

// CompanyIDNotNil applies the NotNil predicate on the "company_id" field.
func CompanyIDNotNil() predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNotNull(FieldCompanyID))
}

// ObjectTypeEQ applies the EQ predicate on the "object_type" field.
func ObjectTypeEQ(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldObjectType, v))
}

// ObjectTypeNEQ applies the NEQ predicate on the "object_type" field.
func ObjectTypeNEQ(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNEQ(FieldObjectType, v))
}

// ObjectTypeIn applies the In predicate on the "object_type" field.
func ObjectTypeIn(vs ...string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldIn(FieldObjectType, vs...))
}

// ObjectTypeNotIn applies the NotIn predicate on the "object_type" field.
func ObjectTypeNotIn(vs ...string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNotIn(FieldObjectType, vs...))
}

// ObjectTypeGT applies the GT predicate on the "object_type" field.
func ObjectTypeGT(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGT(FieldObjectType, v))
}

// ObjectTypeGTE applies the GTE predicate on the "object_type" field.
func ObjectTypeGTE(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGTE(FieldObjectType, v))
}

// ObjectTypeLT applies the LT predicate on the "object_type" field.
func ObjectTypeLT(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLT(FieldObjectType, v))
}

// ObjectTypeLTE applies the LTE predicate on the "object_type" field.
func ObjectTypeLTE(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLTE(FieldObjectType, v))
}

// ObjectTypeContains applies the Contains predicate on the "object_type" field.
func ObjectTypeContains(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldContains(FieldObjectType, v))
}

// ObjectTypeHasPrefix applies the HasPrefix predicate on the "object_type" field.
func ObjectTypeHasPrefix(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldHasPrefix(FieldObjectType, v))
}

// ObjectTypeHasSuffix applies the HasSuffix predicate on the "object_type" field.
func ObjectTypeHasSuffix(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldHasSuffix(FieldObjectType, v))
}

// ObjectTypeEqualFold applies the EqualFold predicate on the "object_type" field.
func ObjectTypeEqualFold(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEqualFold(FieldObjectType, v))
}

// ObjectTypeContainsFold applies the ContainsFold predicate on the "object_type" field.
func ObjectTypeContainsFold(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldContainsFold(FieldObjectType, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldContainsFold(FieldName, v))
}

// ConversionKeyEQ applies the EQ predicate on the "conversion_key" field.
func ConversionKeyEQ(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldConversionKey, v))
}

// ConversionKeyNEQ applies the NEQ predicate on the "conversion_key" field.
func ConversionKeyNEQ(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNEQ(FieldConversionKey, v))
}

// ConversionKeyIn applies the In predicate on the "conversion_key" field.
func ConversionKeyIn(vs ...string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldIn(FieldConversionKey, vs...))
}

// ConversionKeyNotIn applies the NotIn predicate on the "conversion_key" field.
func ConversionKeyNotIn(vs ...string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNotIn(FieldConversionKey, vs...))
}

// ConversionKeyGT applies the GT predicate on the "conversion_key" field.
func ConversionKeyGT(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGT(FieldConversionKey, v))
}

// ConversionKeyGTE applies the GTE predicate on the "conversion_key" field.
func ConversionKeyGTE(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGTE(FieldConversionKey, v))
}

// ConversionKeyLT applies the LT predicate on the "conversion_key" field.
func ConversionKeyLT(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLT(FieldConversionKey, v))
}

// ConversionKeyLTE applies the LTE predicate on the "conversion_key" field.
func ConversionKeyLTE(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLTE(FieldConversionKey, v))
}

// ConversionKeyContains applies the Contains predicate on the "conversion_key" field.
func ConversionKeyContains(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldContains(FieldConversionKey, v))
}

// ConversionKeyHasPrefix applies the HasPrefix predicate on the "conversion_key" field.
func ConversionKeyHasPrefix(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldHasPrefix(FieldConversionKey, v))
}

// ConversionKeyHasSuffix applies the HasSuffix predicate on the "conversion_key" field.
func ConversionKeyHasSuffix(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldHasSuffix(FieldConversionKey, v))
}

// ConversionKeyIsNil applies the IsNil predicate on the "conversion_key" field.
func ConversionKeyIsNil() predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldIsNull(FieldConversionKey))
}

// ConversionKeyNotNil applies the NotNil predicate on the "conversion_key" field.
func ConversionKeyNotNil() predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNotNull(FieldConversionKey))
}

// ConversionKeyEqualFold applies the EqualFold predicate on the "conversion_key" field.
func ConversionKeyEqualFold(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEqualFold(FieldConversionKey, v))
}

// ConversionKeyContainsFold applies the ContainsFold predicate on the "conversion_key" field.
func ConversionKeyContainsFold(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldContainsFold(FieldConversionKey, v))
}

// FieldTypeEQ applies the EQ predicate on the "field_type" field.
func FieldTypeEQ(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldFieldType, v))
}

// FieldTypeNEQ applies the NEQ predicate on the "field_type" field.
func FieldTypeNEQ(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNEQ(FieldFieldType, v))
}

// FieldTypeIn applies the In predicate on the "field_type" field.
func FieldTypeIn(vs ...string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldIn(FieldFieldType, vs...))
}

// FieldTypeNotIn applies the NotIn predicate on the "field_type" field.
func FieldTypeNotIn(vs ...string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNotIn(FieldFieldType, vs...))
}

// FieldTypeGT applies the GT predicate on the "field_type" field.
func FieldTypeGT(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGT(FieldFieldType, v))
}

// FieldTypeGTE applies the GTE predicate on the "field_type" field.
func FieldTypeGTE(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGTE(FieldFieldType, v))
}

// FieldTypeLT applies the LT predicate on the "field_type" field.
func FieldTypeLT(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLT(FieldFieldType, v))
}

// FieldTypeLTE applies the LTE predicate on the "field_type" field.
func FieldTypeLTE(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLTE(FieldFieldType, v))
}

// FieldTypeContains applies the Contains predicate on the "field_type" field.
func FieldTypeContains(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldContains(FieldFieldType, v))
}

// FieldTypeHasPrefix applies the HasPrefix predicate on the "field_type" field.
func FieldTypeHasPrefix(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldHasPrefix(FieldFieldType, v))
}

// FieldTypeHasSuffix applies the HasSuffix predicate on the "field_type" field.
func FieldTypeHasSuffix(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldHasSuffix(FieldFieldType, v))
}

// FieldTypeEqualFold applies the EqualFold predicate on the "field_type" field.
func FieldTypeEqualFold(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEqualFold(FieldFieldType, v))
}

// FieldTypeContainsFold applies the ContainsFold predicate on the "field_type" field.
func FieldTypeContainsFold(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldContainsFold(FieldFieldType, v))
}

// RequiredEQ applies the EQ predicate on the "required" field.
func RequiredEQ(v bool) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldRequired, v))
}

// RequiredNEQ applies the NEQ predicate on the "required" field.
func RequiredNEQ(v bool) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNEQ(FieldRequired, v))
}

// OptionsEQ applies the EQ predicate on the "options" field.
func OptionsEQ(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldOptions, v))
}

// OptionsNEQ applies the NEQ predicate on the "options" field.
func OptionsNEQ(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNEQ(FieldOptions, v))
}

// OptionsIn applies the In predicate on the "options" field.
func OptionsIn(vs ...string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldIn(FieldOptions, vs...))
}

// OptionsNotIn applies the NotIn predicate on the "options" field.
func OptionsNotIn(vs ...string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNotIn(FieldOptions, vs...))
}

// OptionsGT applies the GT predicate on the "options" field.
func OptionsGT(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGT(FieldOptions, v))
}

// OptionsGTE applies the GTE predicate on the "options" field.
func OptionsGTE(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGTE(FieldOptions, v))
}

// OptionsLT applies the LT predicate on the "options" field.
func OptionsLT(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLT(FieldOptions, v))
}

// OptionsLTE applies the LTE predicate on the "options" field.
func OptionsLTE(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLTE(FieldOptions, v))
}

// OptionsContains applies the Contains predicate on the "options" field.
func OptionsContains(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldContains(FieldOptions, v))
}

// OptionsHasPrefix applies the HasPrefix predicate on the "options" field.
func OptionsHasPrefix(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldHasPrefix(FieldOptions, v))
}

// OptionsHasSuffix applies the HasSuffix predicate on the "options" field.
func OptionsHasSuffix(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldHasSuffix(FieldOptions, v))
}

// OptionsEqualFold applies the EqualFold predicate on the "options" field.
func OptionsEqualFold(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEqualFold(FieldOptions, v))
}

// OptionsContainsFold applies the ContainsFold predicate on the "options" field.
func OptionsContainsFold(v string) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldContainsFold(FieldOptions, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustomFieldDefinition) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustomFieldDefinition) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustomFieldDefinition) predicate.CustomFieldDefinition {
	return predicate.CustomFieldDefinition(sql.NotPredicates(p))
}
